### ISSUE TITLE
[Tracker] Experiment plan (Mar)

### ISSUE THREAD

**Issue by yzh119** [uwsampl/sparsetir-artifact#1]
- [ ] Setup sputnik
- [ ] Try [pixelfly attention](https://github.com/HazyResearch/pixelfly) with Triton.
- [ ] Initial experiment on hybrid matrix.
- [ ] BSRMM end-to-end evaluation
- [ ] RGCN end-to-end evaluation
- [x] DGL 0.8 baseline steup
- [ ] Setup TCGNN baseline: https://github.com/YukeWang96/TCGNN-Pytorch
